config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "home#index"
  resources :cars
  get 'costly_cars', to: 'cars#costly_cars'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    column_names + _ransackers.keys
  end

  def self.ransackable_associations(auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s } + _ransackers.keys
  end
end

app/models/car.rb
class Car < ApplicationRecord
  has_many_attached :images

  validate :mgf_year_condition
  enum transmission: {'Petrol': 0, 'Diesel': 1, 'Hybrid': 2}
  enum drive_type: {'Manual': 0, 'Automatic': 1}

  def self.ransackable_attributes(auth_object = nil)
    ["mfg_company", "car_model", "mfg_year", "car_description", "horse_power", "top_speed", "transmission", "drive_type", "car_price"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["blob_id", "created_at", "id", "name", "record_id", "record_type"]
  end

  private

  def mgf_year_condition
    if mfg_year.present? && mgf_year < Date.new(2015)
      errors.add(:mfg_year, 'must be greater than 2015')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :set_car, only: %i[ show edit update destroy ]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to car_path(@car),  notice: 'Car was successfully created'
    else
      render :new, notice: 'An error occured while adding a car!'
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to car_path(@car), notice: "Car was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path, notice: 'Car has been successfully destroyed'
  end

  def costly_cars
    @costly_cars = Car.where('car_price >= ?', 20.0)
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:mfg_company, :car_model, :mfg_year, :car_description, :horse_power, :top_speed, :car_price, images: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Mfg Company:</strong>
    <%= car.mfg_company %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.car_model %>
  </p>

  <p>
    <strong>Horse Power(nM):</strong>
    <%= car.horse_power %>
  </p>

  <p>
    <strong>Top Speed(km/hr):</strong>
    <%= car.top_speed %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= car.mfg_year %>
  </p>

  </p>
    <strong>Car Price:</strong>
    <%= car.car_price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= car.car_description %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
    <% if car.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>
  
        <ul>
          <% car.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :images, style: "display: block" %>
      <%= form.file_field :images, multiple: true %>
    </div>

    <div>
      <%= form.label :mfg_company, style: "display: block" %>
      <%= form.text_field :mfg_company %>
    </div>

    <div>
      <%= form.label :horse_power, style: "display: block" %>
      <%= form.number_field :horse_power, step: "0.01" %>
    </div>

    <div>
      <%= form.label :top_speed, style: "display: block" %>
      <%= form.number_field :top_speed, step: "0.01" %>
    </div>
  
    </div>
      <%= form.label :car_price, style: "display: block" %>
      <%= form.number_field :car_price, step: "0.01" %>
    </div>

    <div>
      <%= form.label :car_model, style: "display: block" %>
      <%= form.text_field :car_model %>
    </div>
  
    <div>
      <%= form.label :mfg_year, style: "display: block" %>
      <%= form.date_field :mfg_year %>
    </div>

    <div>
      <%= form.label :transmission, style: "display: block" %>
      <%= form.select :transmission, options_for_select(Car.transmissions.keys.map { |key| [key.humanize, key] }, selected: @car.transmission), {}, class: "form-control" %>
    </div>

    <div>
      <%= form.label :drive_type, style: "display: block" %>
      <%= form.select :drive_type, options_for_select(Car.drive_types.keys.map { |key| [key.humanize, key] }, selected: @car.drive_type), {}, class: "form-control" %>
    </div>

    <div>
      <%= form.label :car_description, style: "display: block" %>
      <%= form.text_area :car_description %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/cars/costly_cars.html.erb
<p style="color: green"><%= notice %></p>
<br/><center><h1>Garage Doctor</h1><center>

<div id="cars" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px;">
  <% @costly_cars.each do |car| %>
    <div class="card" style="width: 18rem; height: 30rem; margin: 10px;">
      <%= image_tag car.images.first, class: "card-img-top",  style: "height: 150px;", alt: car.car_model if car.images.attached? %>
      <div class="card-body">
        <h5 class="card-title"><%= car.car_model %></h5>
        <p class="card-text"><%= car.car_description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Transmission: </strong> <%= car.transmission %> Nm</li>
        <li class="list-group-item"><strong>Top Speed: </strong> <%= car.top_speed %> km/hr</li>
        <li class="list-group-item"><strong>Price: </strong> <%= car.car_price %> Lakhs</li>
      </ul>
      <div class="card-body">
        <%= link_to "New car", new_car_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Edit', edit_car_path(car) %>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>
<br/><center><h1>Garage Doctor</h1><center>

<div id="cars" style="display: flex; flex-wrap: wrap; justify-content: center; gap: 20px;">
  <% @cars.each do |car| %>
    <div class="card" style="width: 18rem; height: 28rem; margin: 10px;">
      <%= image_tag car.images.first, class: "card-img-top",  style: "height: 150px;", alt: car.car_model if car.images.attached? %>
      <div class="card-body">
        <h5 class="card-title"><%= car.car_model %></h5>
        <p class="card-text"><%= car.car_description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Transmission: </strong> <%= car.transmission %> Nm</li>
        <li class="list-group-item"><strong>Top Speed: </strong> <%= car.top_speed %> km/hr</li>
      </ul>
      <div class="card-body">
        <%= link_to "New car", new_car_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Edit', edit_car_path(car) %>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>
<center>
  <h1><%= @car.car_model %></h1>
  <div class="card" style="width: 18rem;">
    <%= image_tag @car.images.first, class: "card-img-top", alt: @car.car_model if @car.images.attached? %>
    <div class="card-body">
      <h5 class="card-title"><%= @car.car_model %></h5>
      <p class="card-text"><%= @car.car_description %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Horse Power: <%= @car.horse_power %> Nm</li>
      <li class="list-group-item">Top Speed: <%= @car.top_speed %> km/hr</li>
      <li class="list-group-item">Transmission: <%= @car.transmission %></li>
      <li class="list-group-item">Drive: <%= @car.drive_type %></li>
      <li class="list-group-item">Price: <%= @car.car_price %> Lakhs</li>
    </ul>
    <div class="card-body">
      <%= link_to 'Home', cars_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit', edit_car_path(@car) %>
    </div>
  </div>
</center>

app/views/home/index.html.erb
<div id="hero" style="background-image:url('<%= asset_path('background.jpg') %>')" class="d-flex flex-column justify-content-center align-items-center">
  <div class="container text-center" data-aos="fade-up">
    <h1>The team’s mission is to provide you the best deals at the lowest price and that too hastle-free..</h1>
    <p>We have successfully partnered with various dealers to build this network that will provide
      you the best car deals.
      Our goal is to make healthy relations with customer and build network.</p>
    <a href="#about" class="btn-buy-now scrollto">BUY NOW</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GarageDoctor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <!-- <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>  -->
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer
  class="newfooter text-center text-lg-start"
  style="border: 1px solid black"
>
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="https://www.facebook.com" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://www.twitter.com" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://www.google.com" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="https://www.instagram.com" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">COMPANY NAME</h6>
          <p><i class="fas fa-gem me-3"></i>GARAGE DOCTOR</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">ADDRESS</h6>
          <p><i class="fas fa-home me-3"></i>New York, NY 100, US</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">EMAIL</h6>
          <p><i class="fas fa-envelope me-3"></i>mygarage@gmail.com</p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">CONTACT</h6>
          <p><i class="fas fa-phone me-3"></i>999-234-8912</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div
    class="text-center p-3"
    style="background-color: rgba(0, 0, 0, 0.2); color: black"
  >
    © 2024 Copyright :
    <a class="text-white" href="#" style="text-decoration: none; color: black">
      GARAGE DOCTOR
    </a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to 'Garage Doctor', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'View Cars', costly_cars_path, class: 'nav-link' %>
          </li>
          <li class="nav-item"></li>
            <%= link_to 'Buy/Sell', cars_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link logout-link', form: { class: 'd-inline' } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In ", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#">About Us</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Add A Car</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>